/**
 * Build css/themes.generated.css from Eddie's per-theme token builds.
 *
 * Each theme in @brad-frost-web/eddie-design-tokens ships a tokens.css scoped
 * to `:root`, which makes themes mutually exclusive at load time. This script
 * rescopes every non-default theme to `html[data-theme="<name>"]` so the
 * Eddie theme customizer (ed-r-theme-customizer) can switch themes at runtime
 * by setting a class on <html>. The customizer applies a theme via
 * `document.documentElement.className = "<theme>"`, so each theme's tokens are
 * rescoped to a bare class selector (e.g. `.wowee-zowee`). The default `bfw`
 * theme keeps loading via styles.scss at :root; this file carries the alternates.
 *
 * Runs from eleventy.config.js (eleventy.before) so `npm start` and
 * `npm run build` both stay a single command.
 */
const fs = require("fs");
const path = require("path");

const THEMES = [
	"bfw-dark",
	"bfw-v9",
	"altitude",
	"southleft",
	"we-are-here",
	"wowee-zowee",
];

const TOKENS_ROOT = path.join(
	__dirname,
	"..",
	"node_modules",
	"@brad-frost-web",
	"eddie-design-tokens"
);

function buildThemes() {
	const chunks = [
		"/* GENERATED by scripts/build-themes.js — do not edit. */",
	];

	for (const theme of THEMES) {
		const tokensPath = path.join(TOKENS_ROOT, theme, "build", "css", "tokens.css");
		if (!fs.existsSync(tokensPath)) {
			console.warn(`⚠️  Theme tokens not found for "${theme}" — skipping.`);
			continue;
		}
		const css = fs.readFileSync(tokensPath, "utf8");
		// Rescope the top-level :root block to a bare class selector, matching
		// the class ed-r-theme-customizer sets on <html> when a theme is picked.
		const scoped = css.replace(/:root\s*\{/g, `.${theme} {`);
		chunks.push(`/* ---- theme: ${theme} ---- */`);
		chunks.push(scoped);

		// Theme font faces (loaded lazily by the browser only when used).
		const fontsPath = path.join(TOKENS_ROOT, theme, "css", "fonts.css");
		if (fs.existsSync(fontsPath)) {
			chunks.push(`/* ---- fonts: ${theme} ---- */`);
			chunks.push(rewriteFontPaths(fs.readFileSync(fontsPath, "utf8"), theme));
		}
	}

	const outPath = path.join(__dirname, "..", "css", "themes.generated.css");
	fs.writeFileSync(outPath, chunks.join("\n\n"), "utf8");
	console.log(`✅ Wrote ${outPath} (${THEMES.length} runtime themes)`);
}

/**
 * Font files referenced in each theme's fonts.css are relative to the token
 * package (e.g. url("../fonts/foo.woff2")). Rewrite them to the copied
 * location under /css/theme-fonts/<theme>/ and copy the files across.
 */
function rewriteFontPaths(css, theme) {
	const fontSrcDir = path.join(TOKENS_ROOT, theme, "fonts");
	const fontDestDir = path.join(__dirname, "..", "css", "theme-fonts", theme);
	if (fs.existsSync(fontSrcDir)) {
		fs.mkdirSync(fontDestDir, { recursive: true });
		for (const file of fs.readdirSync(fontSrcDir)) {
			fs.copyFileSync(path.join(fontSrcDir, file), path.join(fontDestDir, file));
		}
	}
	return css.replace(/url\(["']?\.\.\/fonts\//g, `url("/css/theme-fonts/${theme}/`);
}

module.exports = { buildThemes };

if (require.main === module) {
	buildThemes();
}
